### ISSUE TITLE
Issue with rune chosen background 

### ISSUE THREAD

**Issue by stikayto** [jcsato/of_flesh_and_faith_plus#1]
Hello,

I'm running a rune chosen campaign and everything was working nice until I added the 2 last runes to a mercenary (death door rune and nemesis rune). Now everytime I tried to start a fight with this mercenary in the fighting line, the fight won't load. I can still load fight if he's resting, this is why I suspect the runes caused the issue.

I'm using version 1.5.0.10 of the game, with all DLC.
Here is the log files :
[log.zip](https://github.com/jcsato/of_flesh_and_faith_plus/files/9924689/log.zip)

This is the list of mods i'm using : 
![Screenshot 2022-11-03 000338](https://user-images.githubusercontent.com/75758451/199618718-90572899-189a-41d3-a0ff-d909866b6f42.png)

**Comment by jcsato** [comment]
Thanks for the report - sorry it took a couple days to get back to you, I haven't had access to a dev machine for a bit. I was unable to reproduce this issue with OFF+ 1.3.2. I suspect it's probably one of your other mods overwriting `tactical_entity_manager` in a way that's incompatible with OFF+, although I can't be certain.

One thing you could try - the current version of the game is 1.5.0.12, a couple patch versions ahead of what you've got installed. I don't recall anything in those patches related to `getAllHostilesAsArray` (the function that's hitting the error, according to your log), but it might be worth grabbing the updates anyway.

I'll leave this open for now in case that fixes it or others run into the same problem and we can perhaps hunt down the incompatible mod (if that is indeed the root cause).

**Comment by stikayto** [comment]
Hello, thanks for getting back to me !

I was not aware that I was not playing the current game version, and after updating the issue is resolved. I can join fight with the runed bro just fine. 

I did not try to identify any potential incompatible mod before updating. 
 
Thanks again for your time !

**Comment by jcsato** [comment]
That's great to hear, glad it's resolved!
